-- MySQL Script generated by MySQL Workbench
-- Wed Apr  8 17:28:22 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `school_inventory` DEFAULT CHARACTER SET utf8 ;
USE `school_inventory` ;

-- -----------------------------------------------------
-- Table `school_inventory`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_inventory`.`Users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `role` VARCHAR(30) NOT NULL,
  `phone` VARCHAR(20) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  CHECK (`role` IN ('admin', 'student')),
  CHECK (`status` IN ('active', 'inactive'))) 
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_inventory`.`Equipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_inventory`.`Equipment` (
  `equipment_id` INT NOT NULL AUTO_INCREMENT,
  `item_name` VARCHAR(100) NOT NULL,
  `category` VARCHAR(50) NOT NULL,
  `serial_number` VARCHAR(100) NOT NULL,
  `condition_status` VARCHAR(20) NOT NULL,
  `availability_status` VARCHAR(30) NOT NULL,
  `location` VARCHAR(100) NULL,
  PRIMARY KEY (`equipment_id`),
  UNIQUE INDEX `serial_number_UNIQUE` (`serial_number` ASC) VISIBLE,
  CHECK (`condition_status` IN ('good', 'fair', 'damaged')),
  CHECK (`availability_status` IN ('available', 'checked_out', 'maintenance')))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_inventory`.`Checkout_Records`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_inventory`.`Checkout_Records` (
  `checkout_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `equipment_id` INT NOT NULL,
  `checkout_date` DATETIME NOT NULL,
  `due_date` DATETIME NOT NULL,
  `return_date` DATETIME NULL,
  `checkout_status` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`checkout_id`),
  INDEX `fk_checkout_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_checkout_equipment_idx` (`equipment_id` ASC) VISIBLE,
  CONSTRAINT `fk_checkout_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `school_inventory`.`Users` (`user_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_checkout_equipment`
    FOREIGN KEY (`equipment_id`)
    REFERENCES `school_inventory`.`Equipment` (`equipment_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CHECK (`checkout_status` IN ('checked_out', 'returned', 'overdue')), 
  CHECK (`due_date` >= `checkout_date`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Views
-- -----------------------------------------------------

-- View 1: All equipment currently available for checkout
CREATE OR REPLACE VIEW `school_inventory`.`vw_available_equipment` AS
SELECT
  `equipment_id`,
  `item_name`,
  `category`,
  `serial_number`,
  `condition_status`,
  `location`
FROM `school_inventory`.`Equipment`
WHERE `availability_status` = 'available';


-- View 2: All active (currently checked-out) items with borrower and equipment details
CREATE OR REPLACE VIEW `school_inventory`.`vw_current_checkouts` AS
SELECT
  cr.`checkout_id`,
  cr.`checkout_date`,
  cr.`due_date`,
  cr.`checkout_status`,
  u.`user_id`,
  CONCAT(u.`first_name`, ' ', u.`last_name`) AS `borrower_name`,
  u.`email`,
  u.`phone`,
  e.`equipment_id`,
  e.`item_name`,
  e.`category`,
  e.`serial_number`,
  e.`location`
FROM `school_inventory`.`Checkout_Records` cr
JOIN `school_inventory`.`Users` u ON cr.`user_id` = u.`user_id`
JOIN `school_inventory`.`Equipment` e ON cr.`equipment_id` = e.`equipment_id`
WHERE cr.`checkout_status` = 'checked_out';


-- View 3: Overdue checkouts — items with checkout_status marked as overdue
CREATE OR REPLACE VIEW `school_inventory`.`vw_overdue_checkouts` AS
SELECT
  cr.`checkout_id`,
  cr.`checkout_date`,
  cr.`due_date`,
  u.`user_id`,
  CONCAT(u.`first_name`, ' ', u.`last_name`) AS `borrower_name`,
  u.`email`,
  u.`phone`,
  e.`equipment_id`,
  e.`item_name`,
  e.`category`,
  e.`serial_number`,
  e.`location`
FROM `school_inventory`.`Checkout_Records` cr
JOIN `school_inventory`.`Users` u ON cr.`user_id` = u.`user_id`
JOIN `school_inventory`.`Equipment` e ON cr.`equipment_id` = e.`equipment_id`
WHERE cr.`checkout_status` = 'overdue';


-- View 4: Full checkout history for all users — useful for admin audit and student history pages
CREATE OR REPLACE VIEW `school_inventory`.`vw_user_checkout_history` AS
SELECT
  cr.`checkout_id`,
  u.`user_id`,
  CONCAT(u.`first_name`, ' ', u.`last_name`) AS `borrower_name`,
  u.`email`,
  u.`role`,
  e.`equipment_id`,
  e.`item_name`,
  e.`category`,
  e.`serial_number`,
  cr.`checkout_date`,
  cr.`due_date`,
  cr.`return_date`,
  cr.`checkout_status`
FROM `school_inventory`.`Checkout_Records` cr
JOIN `school_inventory`.`Users` u ON cr.`user_id` = u.`user_id`
JOIN `school_inventory`.`Equipment` e ON cr.`equipment_id` = e.`equipment_id`
ORDER BY cr.`checkout_date` DESC;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
